#!/bin/bash -e

tomato () {
    echo -e "\U1F345"
}

short_cycle_message () {
    possible_messages=(
    "Short break!"
    "Stand up!"
    "Watch your posture!"
    )
    number_of_possible_messages=3
    echo ${possible_messages[$((RANDOM % number_of_possible_messages))]}
}

long_cycle_message () {
    possible_messages=(
    "LOOOONG BREAK!"
    "Long break. Stand up, take a coffee, look at the window then come back to work."
    "Long break. Please stop working."
    )
    number_of_possible_messages=3
    echo ${possible_messages[$((RANDOM % number_of_possible_messages))]}
}

end_of_rest_message () {
    possible_messages=(
    "End of rest period, get back to work."
    "Your rest period just finished, get back here."
    )
    number_of_possible_messages=2
    echo ${possible_messages[$((RANDOM % number_of_possible_messages))]}
}

message_notification () {
    notify-send "$(tomato) ${1}" --icon=NOTHING
    if [[ ${LOUD} -eq 1 ]]; then
        say "${1}"
    fi
    echo "$(date) [${2}]: \"${1}\""
}

short_cycle () {
    sleep ${SHORT_CYCLE_LENGHT}
    log_message="$(message_notification "$(short_cycle_message)" "SHORT CYCLE")"
    echo ${log_message}
}

last_short_cycle () {
    sleep ${SHORT_CYCLE_LENGHT}
    log_message="$(message_notification "$(long_cycle_message)" "LONG CYCLE")"
    echo ${log_message}
}

rest_cycle () {
    sleep ${REST_LENGTH}
    log_message="$(message_notification "$(end_of_rest_message)" "REST")"
    echo ${log_message}
}

pomodoro_cycle () {
notify-send "Starting cycles. You will see a notification like this."
while true
do
    for i in $( seq 1 $((${NUMBER_OF_SHORT_CYCLES}-1)) )
    do
        echo "$(short_cycle)"
    done
    echo "$(last_short_cycle)"
    echo "$(rest_cycle)"
done
}

SHORT_CYCLE_LENGHT=5 # in minutes
NUMBER_OF_SHORT_CYCLES=4 # The nuber of short breaks until a long break
REST_LENGTH=5 # in minutes
LOUD=0
POMODORO_FILE="${HOME}/.pomodoroid"

# Parsing Arguments
POSITIONAL=()
while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        -n|--number-of-short-cycles)
        NUMBER_OF_SHORT_CYCLES=${2}
        shift # past argument
        shift # past argument
        ;;
        -l|--loud)
        LOUD=1
        ;;
        *)    # unknown option
        POSITIONAL+=("$1") # save it in an array for later
        shift # past argument
        ;;
    esac
done
set -- "${POSITIONAL[@]}"

case ${1} in 
    start)
        echo "$(pomodoro_cycle)" &
        echo $!> ${POMODORO_FILE}
        echo "$(tomato) Pomodoro started!"
        ;;
    stop)
        kill "$(cat ${POMODORO_FILE})"
        rm ${POMODORO_FILE}
        echo "$(tomato) Pomodoro stoped!"
        ;;
    *)
        echo "None of the above."
    ;;

esac
